language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=v2.0.7
  - SYMFONY_VERSION=origin/2.0

before_script:
  - php vendor/vendors.php
  - git clone https://github.com/chobie/php-sundown php-sundown -b development
  - sh -c "cd php-sundown && rake submodule compile && sudo rake install"
  - echo "extension=sundown.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
