language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=v2.0.9
  - SYMFONY_VERSION=origin/2.0

before_script:
  - php vendor/vendors.php
  - wget http://pecl.php.net/get/sundown-0.1.0b.tgz
  - tar -xzf sundown-0.1.0b.tgz
  - sh -c "cd sundown-0.1.0b && phpize && ./configure --enable-sundown && make && sudo make install"
  - echo "extension=sundown.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
